#!/bin/sh
#
# Script to build GDS documentation
#
# Copyright (C) 2000-2004 Institute for Global Environment and Society /
#                        Center for Ocean-Land-Atmosphere Studies
# Author: Joe Wielgosz <joew@cola.iges.org>
#
# Last modified: $Date: 2008/04/16 16:57:29 $ 
# Revision for this file: $Revision: 1.5 $
# Release name: $Name: v2_0 $
# Original for this file: $Source: /homes/cvsroot/gds/gds/src/makedoc,v $

rm -rf ../doc/api
javadoc -protected -windowtitle "GrADS Data Server" -nodeprecatedlist \
-d ../doc/api -sourcepath . \
org.iges.util \
org.iges.anagram \
org.iges.anagram.service \
org.iges.anagram.filter \
org.iges.grads.server \
org.iges.grads.server.dap
